'use strict';

angular.module('ariadneApp')
  .factory('geocodeFactory', function () {
    var demonyms =   {
    "Argentinians":"Argentina",
    "Azeri":"Azerbaijan",
    "Azeris":"Azerbaijan",
    "Banyarwanda":"Rwanda",
    "Barundi":"Burundi",
    "Bosniak":"Bosnia and Herzegovina",
    "Bosniaks":"Bosnia and Herzegovina",
    "Botswanan":"Botswana",
    "Botswanans":"Botswana",
    "Congo":"Dem. Republic of the Congo",
    "Cook Islands":"Cook Islands",
    "Croats":"Croatia",
    "Dutchmen":"Netherlands",
    "Emiri":"United Arab Emirates",
    "Emirian":"United Arab Emirates",
    "Emirians":"United Arab Emirates",
    "Equatoguinean":"Equatorial Guinea",
    "Equatoguineans":"Equatorial Guinea",
    "Filipinas":"Philippines",
    "Filipino":"Philippines",
    "Futunan":"Wallis and Futuna",
    "Futunans":"Wallis and Futuna",
    "Greciang":"Greece",
    "Greciansg":"Greece",
    "Guambat":"Guam",
    "Hellenes":"Greece",
    "Hellenic":"Greece",
    "Herzegovinian":"Bosnia and Herzegovina",
    "Herzegovinians":"Bosnia and Herzegovina",
    "Hongkongese":"Hong Kong",
    "Italic":"Italy",
    "Italics":"Italy",
    "Kazakhs":"Kazakhstan",
    "Kazakhstani":"Kazakhstan",
    "Kirghiz":"Kyrgyzstan",
    "Kirgiz":"Kyrgyzstan",
    "Kosovan":"Kosovo",
    "Kyrgyz":"Kyrgyzstan",
    "Lao":"Laos",
    "Laos":"Laos",
    "Letts":"Latvia",
    "Luxembourgish":"Luxembourg",
    "Magyar":"Hungary",
    "Magyars":"Hungary",
    "Malinese":"Mali",
    "Martinican":"Martinique",
    "Miquelonnais":"Saint-Pierre and Miquelon",
    "Monacan":"Monaco",
    "Monacans":"Monaco",
    "Mongols":"Mongolia",
    "Nepali":"Nepal",
    "Netherlanders":"Netherlands",
    "Netherlandic":"Netherlands",
    "Nevisian":"St. Kitts and Nevis",
    "Nevisians":"St. Kitts and Nevis",
    "NZ":"New Zealand",
    "Papuan":"Papua New Guinea",
    "Papuans":"Papua New Guinea",
    "Persian":"Iran",
    "Persians":"Iran",
    "Réunionnais":"Réunion",
    "Sahraouian":"Western Sahara",
    "Sahraouis":"Western Sahara",
    "Sahrawian":"Western Sahara",
    "Saudi Arabian":"Saudi Arabia",
    "Saudi Arabians":"Saudi Arabia",
    "Scotchi":"Scotland",
    "Scotsmen":"Scotland",
    "Scottish":"Scotland",
    "Serbs":"Serbia",
    "Slovene":"Slovenia",
    "Slovenes":"Slovenia",
    "Tahitians":"French Polynesia",
    "Tajiks":"Tajikistan",
    "Tobagonian":"Trinidad and Tobago",
    "Tobagonians":"Trinidad and Tobago",
    "UK":"United Kingdom",
    "Uzbek":"Uzbekistan",
    "Uzbeks":"Uzbekistan",
    "Vanuatuan":"Vanuatu",
    "Vincentian":"St. Vincent and the Grenadines",
    "Vincentians":"St. Vincent and the Grenadines",
    "Abkhaz":"Abkhazia",
    "Abkhazian":"Abkhazia",
    "Abkhazians":"Abkhazia",
    "Afghan":"Afghanistan",
    "Afghans":"Afghanistan",
    "Albanian":"Albania",
    "Albanians":"Albania",
    "Algerian":"Algeria",
    "Algerians":"Algeria",
    "American":"United States",
    "American Samoan":"American Samoa",
    "American Samoans":"American Samoa",
    "Americans":"United States",
    "Andorran":"Andorra",
    "Andorrans":"Andorra",
    "Angolan":"Angola",
    "Angolans":"Angola",
    "Anguillan":"Anguilla",
    "Anguillans":"Anguilla",
    "Antiguan":"Antigua and Barbuda",
    "Antiguans":"Antigua and Barbuda",
    "Argentine":"Argentina",
    "Argentinean":"Argentina",
    "Argentines":"Argentina",
    "Argentinian":"Argentina",
    "Armenian":"Armenia",
    "Armenians":"Armenia",
    "Aruban":"Aruba",
    "Arubans":"Aruba",
    "Australian":"Australia",
    "Australians":"Australia",
    "Austrian":"Austria",
    "Austrians":"Austria",
    "Azerbaijani":"Azerbaijan",
    "Azerbaijanis":"Azerbaijan",
    "Bahamian":"Bahamas",
    "Bahamians":"Bahamas",
    "Bahraini":"Bahrain",
    "Bahrainis":"Bahrain",
    "Bamar":"Burma",
    "Bangladeshi":"Bangladesh",
    "Bangladeshis":"Bangladesh",
    "Barbadian":"Barbados",
    "Barbadians":"Barbados",
    "Barbudan":"Antigua and Barbuda",
    "Barbudans":"Antigua and Barbuda",
    "Basotho":"Lesotho",
    "Batswana":"Botswana",
    "Belarusian":"Belarus",
    "Belarusians":"Belarus",
    "Belgian":"Belgium",
    "Belgians":"Belgium",
    "Belizean":"Belize",
    "Belizeans":"Belize",
    "Beninese":"Benin",
    "Beninois":"Benin",
    "Bermudan":"Bermuda",
    "Bermudans":"Bermuda",
    "Bermudian":"Bermuda",
    "Bermudians":"Bermuda",
    "Bhutanese":"Bhutan",
    "Bolivian":"Bolivia",
    "Bolivians":"Bolivia",
    "Bosnian":"Bosnia and Herzegovina",
    "Bosnians":"Bosnia and Herzegovina",
    "Brazilian":"Brazil",
    "Brazilians":"Brazil",
    "British":"United Kingdom",
    "British Virgin Island":"British Virgin Islands",
    "British Virgin Islanders":"British Virgin Islands",
    "Britons":"Great Britain",
    "Bruneian":"Brunei",
    "Bruneians":"Brunei",
    "Bulgarian":"Bulgaria",
    "Bulgarians":"Bulgaria",
    "Burkinabè":"Burkina Fasoa",
    "Burmese":"Burma",
    "Burundian":"Burundi",
    "Burundians":"Burundi",
    "Cambodian":"Cambodia",
    "Cambodians":"Cambodia",
    "Cameroonian":"Cameroon",
    "Cameroonians":"Cameroon",
    "Canadian":"Canada",
    "Canadians":"Canada",
    "Cape Verdean":"Cape Verde",
    "Cape Verdeans":"Cape Verde",
    "Caymanian":"Cayman Islands",
    "Caymanians":"Cayman Islands",
    "Central African":"Central African Republic",
    "Central Africans":"Central African Republic",
    "Chadian":"Chad",
    "Chadians":"Chad",
    "Chilean":"Chile",
    "Chileans":"Chile",
    "Chinese":"People's Republic of China",
    "Christmas Island":"Christmas Island",
    "Christmas Islanders":"Christmas Island",
    "Cocos Island":"Cocos (Keeling) Islands",
    "Cocos Islanders":"Cocos (Keeling) Islands",
    "Colombian":"Colombia",
    "Colombians":"Colombia",
    "Comorian":"Comoros",
    "Comorians":"Comoros",
    "Congolese":"Dem. Republic of the Congo",
    "Cook Island":"Cook Islands",
    "Cook Islanders":"Cook Islands",
    "Costa Rican":"Costa Rica",
    "Costa Ricans":"Costa Rica",
    "Croatian":"Croatia",
    "Croatians":"Croatia",
    "Cuban":"Cuba",
    "Cubans":"Cuba",
    "Cypriot":"Cyprus",
    "Cypriots":"Cyprus",
    "Czech":"Czech Republic",
    "Czechs":"Czech Republic",
    "Danes":"Denmark",
    "Danish":"Denmark",
    "Djiboutian":"Djibouti",
    "Djiboutians":"Djibouti",
    "Dominicand":"Dominica",
    "Dominicane":"Dominican Republic",
    "Dominicansd":"Dominica",
    "Dominicanse":"Dominican Republic",
    "Dutch":"Netherlands",
    "Ecuadorian":"Ecuador",
    "Ecuadorians":"Ecuador",
    "Egyptian":"Egypt",
    "Egyptians":"Egypt",
    "Emirati":"United Arab Emirates",
    "Emiratis":"United Arab Emirates",
    "English":"England",
    "Equatorial Guinean":"Equatorial Guinea",
    "Equatorial Guineans":"Equatorial Guinea",
    "Eritrean":"Eritrea",
    "Eritreans":"Eritrea",
    "Estonian":"Estonia",
    "Estonians":"Estonia",
    "Ethiopian":"Ethiopia",
    "Ethiopians":"Ethiopia",
    "Falkland Island":"Falkland Islands",
    "Falkland Islanders":"Falkland Islands",
    "Faroese":"Faroe Islands",
    "Fijian":"Fiji",
    "Fijians":"Fiji",
    "Filipinos":"Philippines",
    "Finnish":"Finland",
    "Finns":"Finland",
    "French":"France",
    "Frenchman":"France",
    "French Guianese":"French Guiana",
    "French Polynesian":"French Polynesia",
    "French Polynesians":"French Polynesia",
    "Gabonese":"Gabon",
    "Gambian":"Gambia",
    "Gambians":"Gambia",
    "Georgian":"Georgia",
    "Georgians":"Georgia",
    "German":"Germany",
    "Germans":"Germany",
    "Ghanaian":"Ghana",
    "Ghanaians":"Ghana",
    "Gibraltar":"Gibraltar",
    "Gibraltarians":"Gibraltar",
    "Greek":"Greece",
    "Greeks":"Greece",
    "Greenlanders":"Greenland",
    "Greenlandic":"Greenland",
    "Grenadian":"Grenada",
    "Grenadians":"Grenada",
    "Guadeloupe":"Guadeloupe",
    "Guadeloupians":"Guadeloupe",
    "Guamanian":"Guam",
    "Guamanians":"Guam",
    "Guatemalan":"Guatemala",
    "Guatemalans":"Guatemala",
    "Guinean":"Guinea",
    "Guineans":"Guinea",
    "Guyanese":"Guyana",
    "Haitian":"Haiti",
    "Haitians":"Haiti",
    "Honduran":"Honduras",
    "Hondurans":"Honduras",
    "Hong Kong":"Hong Kong",
    "Hongkongers":"Hong Kong",
    "Hungarian":"Hungary",
    "Hungarians":"Hungary",
    "I-Kiribati":"Kiribati",
    "Icelanders":"Iceland",
    "Icelandic":"Iceland",
    "Indian":"India",
    "Indians":"India",
    "Indonesian":"Indonesia",
    "Indonesians":"Indonesia",
    "Iranian":"Iran",
    "Iranians":"Iran",
    "Iraqi":"Iraq",
    "Iraqis":"Iraq",
    "Irish":"Republic of Ireland",
    "Israeli":"Israel",
    "Israelis":"Israel",
    "Italian":"Italy",
    "Italians":"Italy",
    "Ivorian":"Côte d'Ivoire",
    "Ivorians":"Côte d'Ivoire",
    "Jamaican":"Jamaica",
    "Jamaicans":"Jamaica",
    "Japanese":"Japan",
    "Jordanian":"Jordan",
    "Jordanians":"Jordan",
    "Kazakh":"Kazakhstan",
    "Kazakhstanis":"Kazakhstan",
    "Kenyan":"Kenya",
    "Kenyans":"Kenya",
    "Kittitian":"St. Kitts and Nevis",
    "Kittitians":"St. Kitts and Nevis",
    "Koreans":"North Korea",
    "Kosovar":"Kosovo",
    "Kosovars":"Kosovo",
    "Kuwaiti":"Kuwait",
    "Kuwaitis":"Kuwait",
    "Kyrgyzstani":"Kyrgyzstan",
    "Kyrgyzstanis":"Kyrgyzstan",
    "Laotian":"Laos",
    "Laotians":"Laos",
    "Latvian":"Latvia",
    "Latvians":"Latvia",
    "Lebanese":"Lebanon",
    "Liberian":"Liberia",
    "Liberians":"Liberia",
    "Libyan":"Libya",
    "Libyans":"Libya",
    "Liechtenstein":"Liechtenstein",
    "Liechtensteiners":"Liechtenstein",
    "Lithuanian":"Lithuania",
    "Lithuanians":"Lithuania",
    "Luxembourg":"Luxembourg",
    "Luxembourgers":"Luxembourg",
    "Macanese":"Macau",
    "Macedonian":"Republic of Macedonia",
    "Macedonians":"Republic of Macedonia",
    "Mahorais":"Mayotte",
    "Mahoran":"Mayotte",
    "Malagasy":"Madagascar",
    "Malawian":"Malawi",
    "Malawians":"Malawi",
    "Malaysian":"Malaysia",
    "Malaysians":"Malaysia",
    "Maldivian":"Maldives",
    "Maldivians":"Maldives",
    "Malian":"Mali",
    "Malians":"Mali",
    "Maltese":"Malta",
    "Manx":"Isle of Man",
    "Marshallese":"Marshall Islands",
    "Martiniquais":"Martinique",
    "Mauritanian":"Mauritania",
    "Mauritanians":"Mauritania",
    "Mauritian":"Mauritius",
    "Mauritians":"Mauritius",
    "Mexican":"Mexico",
    "Mexicans":"Mexico",
    "Micronesian":"Micronesia, Federated States of",
    "Micronesians":"Micronesia, Federated States of",
    "Moldovan":"Moldova",
    "Moldovans":"Moldova",
    "Monégasque":"Monaco",
    "Monégasques":"Monaco",
    "Mongolian":"Mongolia",
    "Mongolians":"Mongolia",
    "Montenegrin":"Montenegro",
    "Montenegrins":"Montenegro",
    "Montserratian":"Montserrat",
    "Montserratians":"Montserrat",
    "Moroccan":"Morocco",
    "Moroccans":"Morocco",
    "Motswana":"Botswana",
    "Mozambican":"Mozambique",
    "Mozambicans":"Mozambique",
    "Namibian":"Namibia",
    "Namibians":"Namibia",
    "Nauruan":"Nauru",
    "Nauruans":"Nauru",
    "Nepalese":"Nepal",
    "New Caledonian":"New Caledonia",
    "New Caledonians":"New Caledonia",
    "New Zealand":"New Zealand",
    "New Zealanders":"New Zealand",
    "Ni-Vanuatu":"Vanuatu",
    "Nicaraguan":"Nicaragua",
    "Nicaraguans":"Nicaragua",
    "Nigerian":"Nigeria",
    "Nigerians":"Nigeria",
    "Nigerien":"Niger",
    "Nigeriens":"Niger",
    "Niuean":"Niue",
    "Niueans":"Niue",
    "none":"Turks and Caicos Islands",
    "North Korean":"North Korea",
    "Northern Irish":"Northern Ireland",
    "Northern Marianan":"Northern Marianas",
    "Northern Marianans":"Northern Marianas",
    "Norwegian":"Norway",
    "Norwegians":"Norway",
    "Omani":"Oman",
    "Omanis":"Oman",
    "Pakistani":"Pakistan",
    "Pakistanis":"Pakistan",
    "Palauan":"Palau",
    "Palauans":"Palau",
    "Palestinian":"Palestine",
    "Palestinians":"Palestine",
    "Panamanian":"Panama",
    "Panamanians":"Panama",
    "Papua New Guinean":"Papua New Guinea",
    "Papua New Guineans":"Papua New Guinea",
    "Paraguayan":"Paraguay",
    "Paraguayans":"Paraguay",
    "Peruvian":"Peru",
    "Peruvians":"Peru",
    "Philippine":"Philippines",
    "Pitcairn Island":"Pitcairn Island",
    "Pitcairn Islanders":"Pitcairn Island",
    "Poles":"Poland",
    "Polish":"Poland",
    "Portuguese":"Portugal",
    "Puerto Rican":"Puerto Rico",
    "Puerto Ricans":"Puerto Rico",
    "Qatari":"Qatar",
    "Qataris":"Qatar",
    "Réunionese":"Réunion",
    "Romanian":"Romania",
    "Romanians":"Romania",
    "Russian":"Russia",
    "Russians":"Russia",
    "Rwandan":"Rwanda",
    "Rwandans":"Rwanda",
    "Sahraw":"Western Sahara",
    "Sahrawis":"Western Sahara",
    "Saint-Pierrais":"Saint-Pierre and Miquelon",
    "Salvadoranf":"El Salvador",
    "Salvadoransf":"El Salvador",
    "Sammarinese":"San Marino",
    "Samoan":"Samoa",
    "Samoans":"Samoa",
    "São Toméan":"São Tomé and Príncipe",
    "São Toméans":"São Tomé and Príncipe",
    "Saudi":"Saudi Arabia",
    "Saudis":"Saudi Arabia",
    "Scots":"Scotland",
    "Senegalese":"Senegal",
    "Serbian":"Serbia",
    "Serbians":"Serbia",
    "Seychellois":"Seychelles",
    "Sierra Leonean":"Sierra Leone",
    "Sierra Leoneans":"Sierra Leone",
    "Singaporean":"Singapore",
    "Singaporeans":"Singapore",
    "Slovak":"Slovakia",
    "Slovaks":"Slovakia",
    "Slovenian":"Slovenia",
    "Slovenians":"Slovenia",
    "Solomon Island":"Solomon Islands",
    "Solomon Islanders":"Solomon Islands",
    "Somali; Somalian":"Somalia",
    "Somalis; Somalians":"Somalia",
    "South African":"South Africa",
    "South Africans":"South Africa",
    "South Korean":"South Korea",
    "South Ossetian":"South Ossetia",
    "South Ossetians":"South Ossetia",
    "South Sudanese":"South Sudan",
    "Spaniards":"Spain",
    "Spanish":"Spain",
    "Sri Lankan":"Sri Lanka",
    "Sri Lankans":"Sri Lanka",
    "St. Helenian":"St. Helena",
    "St. Helenians":"St. Helena",
    "St. Lucian":"St. Lucia",
    "St. Lucians":"St. Lucia",
    "St. Vincentian":"St. Vincent and the Grenadines",
    "St. Vincentians":"St. Vincent and the Grenadines",
    "Sudanese":"Sudan",
    "Surinamers":"Surinam",
    "Surinamese":"Surinam",
    "Swazi":"Swaziland",
    "Swazis":"Swaziland",
    "Swedes":"Sweden",
    "Swedish":"Sweden",
    "Swiss":"Switzerland",
    "Syrian":"Syria",
    "Syrians":"Syria",
    "Taiwanese":"Taiwan",
    "Tajikistani":"Tajikistan",
    "Tajikistanis":"Tajikistan",
    "Tanzanian":"Tanzania",
    "Tanzanians":"Tanzania",
    "Thai":"Thailand",
    "Timorese":"East Timor",
    "Togolese":"Togo",
    "Tongan":"Tonga",
    "Tongans":"Tonga",
    "Trinidadian":"Trinidad and Tobago",
    "Trinidadians":"Trinidad and Tobago",
    "Tunisian":"Tunisia",
    "Tunisians":"Tunisia",
    "Turkish":"Turkey",
    "Turkmen":"Turkmenistan",
    "Turkmens":"Turkmenistan",
    "Turks":"Turkey",
    "Turks and Caicos Islanders":"Turks and Caicos Islands",
    "Tuvaluan":"Tuvalu",
    "Tuvaluans":"Tuvalu",
    "Ugandan":"Uganda",
    "Ugandans":"Uganda",
    "Ukrainian":"Ukraine",
    "Ukrainians":"Ukraine",
    "Uruguayan":"Uruguay",
    "Uruguayans":"Uruguay",
    "Uzbekistani":"Uzbekistan",
    "Uzbekistanis":"Uzbekistan",
    "Venezuelan":"Venezuela",
    "Venezuelans":"Venezuela",
    "Vietnamese":"Vietnam",
    "Virgin Island":"Virgin Islands",
    "Virgin Islanders":"Virgin Islands",
    "Wallisian":"Wallis and Futuna",
    "Wallisians":"Wallis and Futuna",
    "Welsh":"Wales",
    "Yemeni":"Yemen",
    "Yemenis":"Yemen",
    "Zambian":"Zambia",
    "Zambians":"Zambia",
    "Zimbabwean":"Zimbabwe",
    "Zimbabweans":"Zimbabwe"
  }

    // Public API here
    return {
      geocode: function (term, bounds) {
        var search;
        if (demonyms[term]){
          search = demonyms[term];
        } else {
          search = term;
        }
        return search;
      }
    };
  });
